### ISSUE TITLE
Build on Android Failes

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#15]
Fehler mit einem Plugin evtl. Plan builder

**Comment by jaegermathias** [comment]
Habe es gerade überprüft und mein Stand funktioniert im Editor, auf dem Tablet und dem Handy. Der Fehler kommt also von einem der nachfolgenden Commits gestern Abend. Könnten morgen nochmal gemeinsam drüber schauen? Heute wird es bei mir nichts mehr.

**Comment by jaegermathias** [comment]
Ich habe gerade den neuesten Stand ausprobiert und auch der funktioniert bei mir. Das ist wohl eher ein Problem auf deiner Maschine. Probier mal die aktuellste Unity-Version: Unity 5.1.0f3 (32-bit). Gibt tatsächlich schon wieder was Neueres.

**Comment by nerdnuss** [comment]
Das Android SDK hatte in der neuen Unity Version noch keine verlinkung

**Comment by jaegermathias** [comment]
Nicht mehr aktuell, Problem ist gelöst.
