### ISSUE TITLE
Test: Alternative Spielfeldmitte

### ISSUE THREAD

**Issue by jaegermathias** [jaegermathias/Augmented_Party_Game#16]
Bitte probiert den aktuellen Stand aus. Ihr braucht den aktuellen Marker für das Zentrum nicht zu drucken. Die Kamera auf den Bildschirm richten müsste ausreichen. Dann die gewünschte Startposition verdecken. Das Fahrzeug wird pro Spiel nur noch einmal instanziiert, deshalb müsst ihr zum Test einer anderen Position die Anwendung neustarten.

Bitte um Feedback, ob wir einen solchen (vielleicht auch größeren) Marker für die Mitte und zum Spielstart einsetzen wollen. Was haltet ihr von Technik / Vorgehen?

Hier der aktuelle Marker:

![marker_zentrum_quadratisch](https://cloud.githubusercontent.com/assets/5737131/8149474/baf14726-12c4-11e5-8e65-681186211bac.jpg)

**Comment by jaegermathias** [comment]
Vorsicht: Durch den aktuellen Stand (mit neu eingebundenem NetzwerkManager) musste ich die Steuerung und das Fahrzeug-Prefab modifizieren. Ihr könnt aktuell nur das Fahrzeug steuern, das bei Klick auf "LAN Host" im Zentrum erzeugt wird.

**Comment by nerdnuss** [comment]
Problem ist mittlerweile behoben.
Marker ist hüpsch ;)
