### ISSUE TITLE
Recherche Qualcomm Vuforia

### ISSUE THREAD

**Issue by jaegermathias** [jaegermathias/Augmented_Party_Game#2]
Auf Prof Grimms Rat hin sollten wir die Lizenzbedingungen von Qualcomm für Vuforia auf die Eignung für das Projekt prüfen und Informationen zum "Education"-Angebot einholen.

Ergebnisse bitte in die Präsentation einfügen.

**Comment by nerdnuss** [comment]
Starter edition ist for free
was die edu lizenz kann ist noch nicht klar Mail ist aber raus. warte auf antwort

**Comment by jaegermathias** [comment]
https://developer.vuforia.com/library/articles/FAQ/Usage

**Comment by nerdnuss** [comment]
Die Mail ist jetzt 6 Tage her leider noch keine Antwort
