### ISSUE TITLE
Spawnpunkte Initial 1-4

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#20]
Erste Startpunkte Für den Spielstart festlegen/Implementieren

**Comment by nerdnuss** [comment]
Trigger Colider  am Spawn wenn Kollision von einem Fahrzeug den Collider berührt wird die Farbe von dem Material der "Box" übertragen

**Comment by ochstobi** [comment]
Seb das mit den Farben ist ja von dir erledigt. Kann das hier dann geschlossen werden?

**Comment by ochstobi** [comment]
Nun wird beim Farbwechsel die Farbe im Carobjekt gespeichert. Darüber kann dann der richtige Spawnpunkt beim respawn gewählt werden.
