### ISSUE TITLE
Fahrzeugfarbe

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#21]
Fahrzeugfarbe für die einzelnen Spieler (1-4)

**Comment by nerdnuss** [comment]
Färben der Fahrzeuge je nach Spawn funktioniert (löschen der "FarbColide"r ist noch nicht vollzogen).
commit: f5d032f03f34f5b4aa59e2e91e30d9b8f815c1c1

**Comment by jaegermathias** [comment]
Ich bekomme beim Start folgende Fehlermeldung:
NullReferenceException: Object reference not set to an instance of an object
SpawnFarbe.OnTriggerEnter (UnityEngine.Collider other) (at Assets/Scripts/SpawnFarbe.cs:55)

**Comment by ochstobi** [comment]
Teste es bitte nochmlal, irgendwie hab ich ausversehn gestern meine Änderung im car prefab nicht mit commited. Sollte jetzt ohne Exception funktionieren.

**Comment by ochstobi** [comment]
Okay ich habe den Fehler gefunden aber noch nicht beheben können. Das Problem tritt auf , wenn der Cube das Trigger Event auslöst.

**Comment by ochstobi** [comment]
Exception in try catch abgefangen.
BoxCollider nach Start entfernt. Funktioniert gut im "SinglePlayer".
