### ISSUE TITLE
NetworkLobbyManager

### ISSUE THREAD

**Issue by ochstobi** [jaegermathias/Augmented_Party_Game#22]
Beim Starten der Scene Lobby kommt der Fehler: "NetworkLobbyManager no GamePlayer prefab is registered. Please add a GamePlayer prefab. UnityEngine.Networking.NetworkManagerHUD:OnGUI()"

und 

"MissingReferenceException: The variable m_GamePlayerPrefab of NetworkLobbyManager doesn't exist anymore."

Starten über ap scene geht. Aber da wird der Marker nur als graue Plattform angezeigt, dadurch ist das Testen mit der Spawnposition sehr schlecht.

**Comment by jaegermathias** [comment]
Der Start über die ap-Szene kann nicht funktionieren. Es muss in jedem Fall über die Lobby gestartet werden.

Ich denke ich habe einen Weg gefunden, wie die zugewiesenen Prefabs erhalten bleiben: Ist (beispielsweise dem NetworkManager) alles zugewiesen, sollte dieser Stand in einem eigenen Prefab festgehalten werden. Es scheint als bliebe der Stand eines Prefabs so erhalten.

Ich hoffe dies hat sich erledigt, ansonsten neu eröffnen.
