### ISSUE TITLE
Virtuelle Überlagerung des physikalischen MultiTargets

### ISSUE THREAD

**Issue by jaegermathias** [jaegermathias/Augmented_Party_Game#29]
Es wäre einen Versuch wert, das physikalische Target in der Spielsszene mit einem virtuellen Objekt zu überlagern. Dabei könnte ein Gebäudemodell zum Einsatz kommen, sodass die Spielfläche das Gebäudedach darstellt.

Meiner Ansicht nach erreicht man hierdurch einen höheren Grad an Augmented Reality, da das "Spielfeld" mit einbezogen wird und erhält gestalterrische Freiräume durch etwa die Erweiterung der befahrbaren Fläche durch überhängende Dachvorsprünge.

**Comment by nerdnuss** [comment]
Finde ich gut. der Dummy steigert schon jetzt erheblich die emersion
