### ISSUE TITLE
Respawn Implementieren

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#31]
In der aktuellen Version fehlt der Respawn 
müsste wieder implementiert werden.
Da Mittlerweile die Spielfläche sowohl Virtuell also auch der Top Marker nicht mehr auf 0 sind sondern in gewisser höher könnte man eine Boden platte Implementieren die ein Liegenbleiben der Fahrzeuge (bis zum Respawn) ermöglicht. Damit könnte die Emersion weiter gesteigert werden da so die Fahrzeuge auf dem "Tisch" liegen bleiben und nicht durch ihn Hindurch zu fallen scheinen.
Die Bodenplatte an sich müsste nicht mal sichtbar sein da der Tisch in der echten Welt ja existiert.

Alternativ wäre auch eine art Wolkenschicht denkbar durch die die Fahrzeuge fallen. Steigert den Höhen effect des Gebäudes da man so den "Boden" nicht sieht.

**Comment by ochstobi** [comment]
Ich werd mich diese Woche an den Respawn machen, bin bisher nicht dazu gekommen.
