### ISSUE TITLE
Touch Steuerung

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#46]
Die Touch Steuerung gibt wenn man aufs gas tippt solang gas bis man den brems/Rückwärtsbutton drückt (fährt also auch wenn es nicht mehr gedrückt wird). Im Rückwärtsgang ist dies vergleichbar. lenken mit Gyroskop funktioniert gut.

**Comment by jaegermathias** [comment]
Ist doch super?
