### ISSUE TITLE
Weiteres Interaktives AR Element (Power Up)

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#50]
Es soll das Spiel um ein weiteres Optionales AR Element neben der Karte (Image Marker), und dem Vulkan ("Cylinder Image-Marker") erweitert werden. Denkbar wären ein Objekt was mittels "Object Recognition" in das Spiel eingebaut wird (Vorher Scan und dann fixes Objekt). Genutzt werden könnte das Objekt als bewegbares Hindernis auf der Spielfläche oder als "Bumper" der bei Berührung Fahrzeuge stark abstößt.

**Comment by jaegermathias** [comment]
Super Idee! ;-)
Ich freu mich auf die Umsetzung. Wenn ich das richtige Netzwerkverhalten fuer #49 gefunden habe, dann werde ich hierauf verweisen, da es sich um das selbe Problem handeln wird: Was läuft wo und was wird wie mit wem synchronisiert. Ich arbeite daran.

**Comment by nerdnuss** [comment]
Idee: den Marker als "Powerup"- Position zu nutzen. In gewissen Abständen erscheint auf dieser Position ein "Plus" in Grün oder Rot. Wenn einer der Spieler über das Grüne Kreuz fährt erhält er ein weiteres Leben. Wenn er über ein Rotes fährt verliert er eins.
