### ISSUE TITLE
Kamera Bug

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#7]
In der APK wird in unregelmäßigen Abständen die Occlusion-Textur des Autos im Vollbild über die Szene gelegt.

**Comment by jaegermathias** [comment]
Ich habe die Beta der nächsten Version (https://unity3d.com/unity/beta) ausprobiert und tatsächlich wurde das Problem behoben! App läuft ohne die Darstellungsfehler der vorigen Version.

Entscheidende Zeile des Release-Notes ist wohl diese hier:
Android: Fixed native plugins that were using GL ES textures
