### ISSUE TITLE
Respawn des Scooters

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#8]
Nachdem der Scooter von der Map gefallen ist wird er wieder auf seinen Spawn-Punkt in der Map gesetzt. (Vorherige Überprüfung ob belegt)

**Comment by nerdnuss** [comment]
Vielleicht anfänglich keine Kollision (Godmode). Semi-Transparentes oder Blinkendes Modell

**Comment by ochstobi** [comment]
Respawn funktioniert jetzt auch ohne Bewegung mit Trigger von einer unterliegenden Plane.
Spawn auf den richtigen Punkt folgt.

**Comment by ochstobi** [comment]
Respawn funktioniert nun auf dem Marker, welcher die gleiche Farbe wie das Auto hat.
