### ISSUE TITLE
Dynamische Map-größe anhand von Markern

### ISSUE THREAD

**Issue by nerdnuss** [jaegermathias/Augmented_Party_Game#9]
Die Größe der Spielwelt soll anhand von mehreren Markern definiert werden.
Einer als Mittelpunkt und weitere als Maxima.
Aktuelle Idee Mittelpunkt mittels Image-Marker.
Rand-Makierung mittels Frame-Marker

**Comment by jaegermathias** [comment]
Mal ganz doof gefragt: Da der Innenbereich der FrameMarker frei zu gestalten ist, könnte man diese Fläche doch auch mit einem ImageTarget belegen...? Also zwei Marker in einem verbinden. Wenn man FrameMarker z.B. für Powerups oder ähnliches benutzt, indem man sie auf den Tisch legt, dann könnte ein ImageTarget im frei gestaltbaren Innenbereich ganz nebenbei die Grundfläche stabilisieren?

**Comment by jaegermathias** [comment]
FrameMarker sind für das weitere Vorgehen ausgeschlossen, da sie in der Erkennung schlichtweg nicht rubous genug sind.

Closed, weil nach aktuellem Vorgehen keine Relevanz mehr.
